ROBOFLOW_BROADCAST_PROJECT = "footy-track-broadcast-frame"
ROBOFLOW_BROADCAST_PROJECT_TEST_PROJECT = "footy-track-broadcast-frame-test"
ROBOFLOW_DETECTION_PROJECT = "footy-track-detection"
ROBOFLOW_DETECTION_PROJECT_TEST_PROJECT = "footy-track-detection-test"
ROBOFLOW_WORKSPACE = "egroeg121"


IMAGE_FORMAT = "png"
BALL_TAG = "ball"
PERSON_TAG = "person"
OUT_OF_PLAY_BALL_TAG = "out_of_play_ball"
IN_PLAY_BALL_TAG = "in_play_ball"
PLAYER_TAG = "player"
PLAYER_SUB_TAG = "player_sub"
REFEREE_TAG = "referee"
COACH_TAG = "coach"
